### ISSUE TITLE
구글 로그인 할때 백엔드하고 API 연결에 대해 문제가 있었습니다.

### ISSUE THREAD

**Issue by baeg-jae** [kevinkim910408/Hexagona_Front#37]
백엔드와 연결이 잘되지 않습니다.

**Comment by kevinkim910408** [comment]
저도 궁금합니다

**Comment by baeg-jae** [comment]
scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none`
  );을 추가해주니 기능이 작동하였습니다.

**Comment by baeg-jae** [comment]
완료!!
